apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: akri-s7-discovery-daemonset
  labels:
    app.kubernetes.io/part-of: akri
    app.kubernetes.io/instance: release-name
    app.kubernetes.io/version: "0.12.20"
    app.kubernetes.io/name: akri-s7-discovery
    app.kubernetes.io/component: discovery-handler
spec:
  selector:
    matchLabels:
      app.kubernetes.io/part-of: akri
      app.kubernetes.io/instance: release-name
      app.kubernetes.io/name: akri-s7-discovery
  template:
    metadata:
      labels:
        app.kubernetes.io/part-of: akri
        app.kubernetes.io/instance: release-name
        app.kubernetes.io/version: "0.12.20"
        app.kubernetes.io/name: akri-s7-discovery
        app.kubernetes.io/component: discovery-handler
    spec:
      containers:
      - name: akri-s7-discovery
        image: "edgenesis/shifu-akri-s7-discovery:nightly"
        resources:
          requests:
            memory: 11Mi
            cpu: 10m
          limits:
            memory: 24Mi
            cpu: 24m
        env:
        - name: DISCOVERY_HANDLERS_DIRECTORY
          value: /var/lib/akri
        volumeMounts:
        - name: discovery-handlers
          mountPath: /var/lib/akri
      nodeSelector:
        "kubernetes.io/os": linux
      volumes:
      - name: discovery-handlers
        hostPath:
          path: /var/lib/akri
---
apiVersion: akri.sh/v0
kind: Configuration
metadata:
  name: s7
spec:
  discoveryHandler: 
    name: s7
    discoveryDetails: "bj-hikcamera-01.saifai.cn:40102"
  brokerProperties:
    DEVICESHIFU_CONFIG: "deviceshifu-s7-configmap"
